---
- name: Configure hostname - Cisco
  hosts: cisco
  gather_facts: no
  tasks:
          - name: Configure router hostname
            cisco.ios.ios_config:
              lines: hostname "{{ hostname }}"
          - name: Configure security banner
            cisco.ios.ios_banner:
              banner: login
              text: "{{ lookup('file', '/etc/ansible/network-automation/config_files/banner.cfg') }}"
              state: present
