---
# WRITTEN BY NIVALDO RAMOS NETO - Sr. Network Engineer

# Palo Alto - Firewall Rules
- name: Add Firewall Rules
  paloaltonetworks.panos.panos_security_rule:
    provider: '{{ palo_provider }}'
    rule_name: "{{ item.rule_name }}"
    description: "{{ item.rule_description|default(omit)  }}"
    source_zone: "{{ item.source_zone }}"
    destination_zone: "{{ item.destination_zone }}"
    source_ip: "{{ item.source_ip }}"
    source_user: "{{ item.source_user|default(omit)  }}"
    destination_ip: "{{ item.destination_ip }}"
    category: "{{ item.category_name|default(omit)  }}"
    application: "{{ item.application_name }}"
    service: "{{ item.service_name }}"
    log_start: "{{ item.log_start }}"
    log_end: "{{ item.log_end }}"
    action: "{{ item.rule_action }}"
    state: "{{ item.rule_state }}"
  when: item.rule_name is defined
  loop: "{{ firewall_rules }}"